### ISSUE TITLE
What's the right way to use this image?

### ISSUE THREAD

**Issue by meteorlxy** [dockhippie/dst#1]
I start the server via docker-compose.
My `docker-compose.yml`:
```
version: '2'

services:
  dst_server:
    container_name: dst_server
    image: webhippie/dst:latest
    ports:
      - 10999:10999/udp
      - 10888:10888/udp
    volumes:
      - ./volumes/save:/game/server/save
    environment:
      - DST_SERVER_TOKEN=my_token
      - DST_SERVER_NAME=my_server_name
      - DST_SERVER_DESC=my_server_desc
      - DST_SERVER_PORT=10999
      - DST_SERVER_INTENTION=cooperative
      - DST_SERVER_PASSWORD=my_pwd
      - DST_GAME_MODE=endless
      - DST_MAX_PLAYERS=10
      - DST_TICK_RATE=30
      - DST_CONNECTION_TIMEOUT=10000
      - DST_SERVER_SAVE_SLOT=1
      - DST_WHITELIST_SLOT=5
      - DST_PVP=false
      - DST_PAUSE_WHEN_EMPTY=true
      - DST_ENABLE_SNAPSHOTS=true
      - DST_ENABLE_AUTOSAVER=true
      - DST_ENABLE_VOTE_KICK=true
      - DST_OFFLINE_SERVER=false
      - DST_SHARD_ENABLE=true
      - DST_SHARD_NAME=127.0.0.1
      - DST_SHARD_ID=1
      - DST_CLUSTER_KEY=mydstserver
      - DST_PRESET=
      - DST_MASTER=true
      - DST_MASTER_IP=127.0.0.1
      - DST_MASTER_PORT=10888
      - DST_STEAM_DISABLE_CLOUD=true
      - DST_STEAM_AUTH_PORT=8766
      - DST_STEAM_MASTER_PORT=27016
      - DST_GENERAL_MODS=my_mods_list
```
After `docker-compose up`, an error occurs:
```
dst_server    | [00:00:05]: [200] Account Failed (6): "E_INVALID_TOKEN"
dst_server    | [00:00:05]: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
dst_server    | [00:00:05]: !!!! Your Server Will Not Start !!!!
dst_server    | [00:00:05]: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
dst_server    | [00:00:05]: No auth token could be found.
``` 
So I create `cluster_token.txt` in `/game/server/Cluster_1/` manually, and it starts successfully.

Then I notice that the server  is not configured correctly, so I have to create `cluster.ini`  in `/game/server/Cluster_1/` again.

The server finally runs... But I want to know what's wrong with my operation? What's the right way to use this image?
